Fix unit test?
Context: https://github.com/xamarin/java.interop/pull/834#issuecomment-838802709
Context: https://gist.github.com/jonpryor/41a0a920d27e5a761f499da4ade791a8

I was operating under the (deluded?) assumption that it should be
possible to use the XML within
`WriteBoundMethodAbstractDeclarationWithGenericReturn()` to reproduce
the `NullReferenceException`, but I was unable to do so.

I thus returned to the [full API declaration][0] to recreate a minimal
test case which *would* result in a `NullReferenceException`, and found
one.

Oddly, the "missing piece" to trigger the NRE was *nested types* (?!):
the original PR #834 had `RangeIterator` as a top-level type, and in
this situation I wasn't able to get an NRE with main.

Once I "reverted" it to a nested `FlowIterator.RangeIterator` type,
it broke.

I don't know if that's the *only* relevant change, as I changed other
pieces as well:

  * Simpler (no parameters) `next()` method
  * Fixed the `//interface/@jni-signature` value for `FlowIterator`

Regardless, this "newer" XML *does* crash, but also only with
`--codegen-target=XAJavaInterop1`.  It doesn't NRE w/o `--codegen-target`:

    $ mono bin/Debug/generator.exe -o yyy ji-834-fixed.xml --codegen-target=XAJavaInterop1
    …
    Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object
      at Xamarin.SourceWriter.MethodWriter.WriteReturnType (Xamarin.SourceWriter.CodeWriter writer)
      at Xamarin.SourceWriter.MethodWriter.WriteSignature (Xamarin.SourceWriter.CodeWriter writer)
      at Xamarin.SourceWriter.MethodWriter.Write (Xamarin.SourceWriter.CodeWriter writer)

[0]: https://github.com/xamarin/java.interop/pull/834#issuecomment-838954034