Fix dotnet/android build
Context: https://github.com/dotnet/android/pull/9750

dotnet/android#9750 attempts to test dotnet/java-interop#1302, and it
failed to build!

    …/src/Mono.Android/obj/Release/net10.0/android-35/mcw/Java.Util.Jar.Pack200.cs(229,54): error CS1109:
    Extension methods must be defined in a top level static class; IPackerExtensions is a nested class

Indeed, what we actually had was:

    abstract partial class Pack200 {
      public partial interface IPacker { /* … */ }

      static partial class IPackerExtensions {
        public static void Pack (this IPacker packer, Stream output, Stream input)
        {
          …
        }
      }
    }

`static` classes containing extension methods must be top-level,
and `IPackerExtensions` is instead nested within `Pack200`.

Fix `generator` so that this doesn't happen.