[generator] fix regression for types from assemblies, take 2!
Context: https://github.com/xamarin/java.interop/commit/84014f4a735f65c3aa666597f05ce6de7d984bb6
Context: https://github.com/xamarin/java.interop/commit/19bcca50934ff7a2464e8d6170eadbba10c2b266

In trying to make the `SymbolTable` class non-static, there was one
place in the `GenBaseSupport` class that needed to use the
`SymbolTable`. My first attempt to workaround this was to move some of
the logic in `GenBaseSupport`'s constructor to an `OnValidate` method.
Unfortunately this breaks alot of things, since it requires `Validate`
to be called for any `ManagedClassGen` or `ManagedInterfaceGen`.

Things are further complicated when you try a large set of input, such
as what happens during `xamarin-android`'s build. Calling `Validate`
was getting exceptions such as:

    Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object
        at Xamarin.Android.Tools.ApiXmlAdjuster.JavaTypeName.Parse (System.String dottedFullName)
        at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Parse (Xamarin.Android.Tools.ApiXmlAdjuster.JavaApi api, System.String name, Xamarin.Android.Tools.ApiXmlAdjuster.JavaTypeParameters[] contextTypeParameters)
        at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.ResolveType (Xamarin.Android.Tools.ApiXmlAdjuster.JavaType type)
        at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Resolve (Xamarin.Android.Tools.ApiXmlAdjuster.JavaInterface i)
        at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Resolve (Xamarin.Android.Tools.ApiXmlAdjuster.JavaApi api)
        at Xamarin.Android.Tools.ApiXmlAdjuster.Adjuster.Process (System.String inputXmlFile, MonoDroid.Generation.GenBase[] gens, System.String outputXmlFile, System.Int32 reportVerbosity)
        at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options, Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver)
        at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options)
        at Xamarin.Android.Binder.CodeGenerator.Main (System.String[] args)

Since reordering initialization in `generator` is causing failures, I
thought it best to put the initialization of the `GenBaseSupport` type
the way it was:

- Pass in `CodeGenerationOptions` to `ManagedClassGen` and
  `ManagedInterfaceGen`, so they have an instance of `SymbolTable`
- Move all the logic from `GenBaseSupport` `OnValidate` to its
  constructor
- We don't need to call `Validate` as early in `CodeGenerator`

Sadly this gets us a little further away from POCOs, but gets things
working again. We can revisit this later when we have more tests. I
think adding support for multiple assemblies in `generator`'s
integration tests would help catch these failures earlier.