[generator] Ensure "global::" is prepended to generic return casts. (#838)
Context: https://github.com/xamarin/xamarin-android/issues/5894

When creating the cast from a generic type parameter (which is
currently always `Java.Lang.Object`), `global::` is not prepended to
the type cast:  

	return (Java.Lang.Object) global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (__rm.Handle, JniHandleOwnership.TransferLocalRef);

This creates a compilation error if the bound type is in a namespace
that ends in `.Java`, such as `MyProduct.Java`.

	Error CS0234: The type or namespace name 'Lang' does not exist in the namespace 'MyProduct.Java'.

Fix this by ensuring the cast output goes through our standard type
formatting method which adds `global::` when needed.