[Interop-Tests] Fix JavaExceptionTests.StackTrace() for Android.
Unsurprisingly, Android throws a different exception type and message
frmo the JVM when JNIEnv::FindClass() can't find a type:

		INSTRUMENTATION_RESULT: failure: Java.InteropTests.JavaExceptionTests.StackTrace=  Expected string length 30 but was 321. Strings differ at index 0.
		  Expected: "this/type/had/better/not/exist"
		  But was:  "Didn't find class "this.type.had.better.not.exist" on path: D..."
		  -----------^

		  at Java.InteropTests.JavaExceptionTests.StackTrace () [0x00000] in <filename unknown>:0
		  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
		  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0

As it happens, Android throws the WRONG type; it should throw
java.lang.NoClassDefFoundError, as the JVM does -- the JNI docs do not
list java.lang.ClassNotFoundException as a type that can be thrown:

	http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#FindClass
> THROWS:
> ClassFormatError: if the class data does not specify a valid class.
>
> ClassCircularityError: if a class or interface would be its own superclass or superinterface.
>
> NoClassDefFoundError: if no definition for a requested class or interface can be found.
>
> OutOfMemoryError: if the system runs out of memory.

Alter the test (via gratuitous use of `#if __ANDROID__`) so that it
passes when running on Android.