[jnimarshalmethod-gen] fixes for interfaces
When bumping xamarin-android to java.interop/master, we are hitting a
failure:

    Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
    Parameter name: propertyName
    System.ArgumentException: Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
    Parameter name: propertyName
        at System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression expression, System.String propertyName) [0x00051] in <9536922a6deb4f2dbdd3b7dedc620be3>:0
        at Java.Interop.JavaPeerableValueMarshaler.CreateIntermediaryExpressionFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue) [0x0002e] in external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs:620
        at Java.Interop.JavaPeerableValueMarshaler.CreateReturnValueFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue) [0x00001] in external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs:631
        at Java.Interop.MarshalMemberBuilder.CreateMarshalToManagedExpression (System.Reflection.MethodInfo method, Java.Interop.JavaCallableAttribute callable, System.Type type) [0x0042d] in external/Java.Interop/src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs:207
        at Java.Interop.MarshalMemberBuilder.CreateMarshalToManagedExpression (System.Reflection.MethodInfo method) [0x00017] in external/Java.Interop/src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs:32
        at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly (System.String path) [0x003fc] in external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:393
        at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1[T] assemblies) [0x00150] in external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:186

Since ef092a8 introduced some changes to interfaces, there are a
couple spots in `jnimarshalmethod-gen.exe` that need a fix.

First, there was an additional cast needed where an interface might
extend `IJavaPeerable`:

    interface IListAdapter : IJavaPeerable { }

After this, we got a new error:

    System.ArgumentException: 'this' type cannot be an interface itself
        at System.RuntimeType.GetInterfaceMap (System.Type ifaceType) [0x00069] in <2d5573434b724f28896144eecd6f4489>:0
        at Xamarin.Android.Tools.JniMarshalMethodGenerator.Extensions.NeedsMarshalMethod (Mono.Cecil.MethodDefinition md, Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver, System.Reflection.MethodInfo method, System.String& name, System.String& methodName, System.String& signature) [0x0006b] in external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:642
        at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly (System.String path) [0x00370] in external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:374
        at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1[T] assemblies) [0x00150] in external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:186

For this one, we can actually skip processing of interfaces -- we
don't need to generate marshal methods for interfaces at all.

I also updated `ExportTest.cs` so it included a problematic interface.
Before these fixes, I could repro the same problems with `make
run-test-jnimarshal`.