[build] Fix the XAIntegrationDebug Configuration Build. (#31)
The XAIntegrationDebug configuration build was broken, for two
reasons:

 1. `make xa-all` wasn't restoring nuget packages:

		repl.cs(43,24): error CS0234: The type or namespace name `Terminal'
		does not exist in the namespace `Mono'.
		Are you missing an assembly reference?

 2. `generator-Tests` was part of the XAIntegrationDebug
    configuration, but `generator` was not. This meant that
    `generator-Tests` project couldn't build.

		BaseGeneratorTest.cs(7,23): error CS0234: The type or namespace
		name `Binder' does not exist in the namespace `Xamarin.Android'.
		Are you missing an assembly reference?

Fix the XAIntegrationDebug and XAIntegrationRelease
configuration mappings.