[Xamarin.Android.Tools.Bytecode] Fix the build
The cherry-pick of commit 439bd839 on master as fe7421dd on d16-5
broke the d16-5 build, because 439bd839 occurred *after* ff3081d0,
which migrated `Xamarin.Android.Tools.Bytecode.csproj` to an
SDK-style/short-form project, and thus the added file
`KotlinUtilities.cs` was implicitly included in the master build, but
was *not* included in the d16-5 build.  The result was a build break:

	Kotlin/KotlinFixups.cs(35,26): error CS1061: 'ClassAccessFlags' does not
	contain a definition for 'IsPubliclyVisible' and no accessible extension
	method 'IsPubliclyVisible' accepting a first argument of type
	'ClassAccessFlags' could be found (are you missing a using directive or
	an assembly reference?)

Explicitly add `KotlinUtilities.cs` to
`Xamarin.Android.Tools.Bytecode.csproj` so that it now builds.