Avoid JDK 14.
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4666262&view=logs&j=54b9b405-417c-5884-5043-18b5f5d9acb9&t=ac76063e-e016-5aec-2585-53fde878edd6

The build is breaking:

	_BuildJava:
	  "/Users/runner/work/1/s/build-tools/gradle/gradlew" -d --stacktrace --no-daemon -PjavaSourceVer=1.8 -PjavaTargetVer=1.8 jar
	  …
	  [ERROR] [system.err] java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	  [ERROR] [system.err] 	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)

Java.Interop/main builds using adoptopenjdk-8.jdk, while this build
is failing with adoptopenjdk-14, as inferred from:

	gcc -g -shared -m64 -fPIC -o bin/TestRelease/libNativeTiming.dylib tests/NativeTiming/timing.c
	  -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include
	  -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include/darwin

Build with `make prepare all JI_MAX_JDK=11`, so that we avoid
AdoptOpenJDK 14.