[Java.Interop] Add JniInstanceMethods.InvokeAbstract*Method()
A problem with integrating Java.Interop and Xamarin.Android: there are
actually *three* "calling conventions" of consequence for binding Java
methods:

  * Nonvirtual method invocation
  * Virtual method invocation
  * Abstract method invocation

Nonvirtual method invocation involves only invoking the specified
method, not any overloads. This isn't typically used, but could be
used for binding `final` methods, as they can't be overridden.

Virtual method invocation involves invoking the most "specific" method
overload available on the runtime type, but *if* (when)
JniPeerMembers.ManagedPeerType isn't equal to the runtime type, we
instead do a *nonvirtual* invocation. This is necessary to support
`base.MethodName()` invocation.

These are the two mechanisms that have previously been supported, but
there is a third invocation pattern: abstract method invocation.

Specifically, consider java.lang.Number:

	public abstract class Number {
		public abstract double doubleValue();
	}

How should this be bound? Surely, says I, we use virtual invocation:

	// C# binding
	public abstract class Number {
		internal static JniPeerMembers _members = new JniPeerMembers ("java/lang/Number", typeof (Number));

		public abstract double DoubleValue();
	}

	internal class NumberInvoker {
		public override unsafe double DoubleValue ()
		{
			const string id = "doubleValue\u0000()D";
			return _members.InvokeVirtualDoubleMethod (id, this, null);
		}
	}

However, that FAILS AT RUNTIME for subclasses, because
JniPeerMembers.JniInstanceMethods.InovkeVirtualDoubleMehtod() will say
"the runtime type of `this` isn't Number, so therefore we want to do a
`super.doubleValue()` invocation!"

This fails because there isn't a super method to invoke [0].

Oops.

This in turn strongly suggests that JniPeerMembers.JniInstanceMethods
needs to directly support this, and so we introduce the
InvokeAbstract*Method() family which perform *only* virtual method
invocations:

	partial class JniInstanceMethods {
		public void   InvokeAbstractVoidMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters);
		public bool   InvokeAbstractBooleanMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public sbyte  InvokeAbstractSByteMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public char   InvokeAbstractCharMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public short  InvokeAbstractInt16Method (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public int    InvokeAbstractInt32Method (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public long   InvokeAbstractInt64Method (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public float  InvokeAbstractSingleMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public double InvokeAbstractDoubleMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
		public JniObjectReference InvokeAbstractObjectMethod (string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
	}

[0]:
INSTRUMENTATION_RESULT: failure: Xamarin.Android.RuntimeTests.ApplicationTest.EnsureAndroidManifestIsUpdated=Java.Lang.AbstractMethodError : abstract method "android.content.pm.ActivityInfo android.content.pm.PackageManager.getActivityInfo(android.content.ComponentName, int)"
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (JniObjectReference object, JniObjectReference klass, Java.Interop.JniInstanceMethodInfo method, Java.Interop.JniArgumentValue* args) <0xaeeca9f8 + 0x001cc> in <filename unknown>:0
  at Java.Interop.JniInstanceMethodInfo.InvokeNonvirtualObjectMethod (JniObjectReference this, JniObjectReference declaringType, Java.Interop.JniArgumentValue* parameters) <0xaeeca958 + 0x0005f> in <filename unknown>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) <0xaeec8788 + 0x00187> in <filename unknown>:0
  at Android.Content.PM.PackageManagerInvoker.GetActivityInfo (Android.Content.ComponentName component, PackageInfoFlags flags) [0x0002f] in .../src/Mono.Android/platforms/android-23/src/generated/Android.Content.PM.PackageManager.cs:2597
  at Xamarin.Android.RuntimeTests.ApplicationTest.EnsureAndroidManifestIsUpdated () [0x00028] in /Users/jon/Dropbox/Developer/xamarin/monodroid-jonp/tests/runtime/Android.App/ApplicationTest.cs:56
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in .../mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:295
  --- End of managed exception stack trace ---
java.lang.AbstractMethodError: abstract method "android.content.pm.ActivityInfo android.content.pm.PackageManager.getActivityInfo(android.content.ComponentName, int)"
	at md5e0d9a58f8ef4c80c20dd923cca887f60.TestSuiteInstrumentation.n_onStart(Native Method)
	at md5e0d9a58f8ef4c80c20dd923cca887f60.TestSuiteInstrumentation.onStart(TestSuiteInstrumentation.java:67)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)