Use DotNetCoreVersion 6.0.x
We think this was bumped to a specific preview6 version because of:

https://discord.com/channels/732297728826277939/732297837953679412/874959446747533323

    error CS8400: Feature 'interpolated string handlers' is not available in C# 8.0. Please use language version 10.0 or greater.

However, is it still needed?