[jnimarshalmethod-gen] Add `-o DIR` option (#408)
Context: https://github.com/xamarin/xamarin-android/pull/2454#issuecomment-448551497
Context: https://github.com/xamarin/xamarin-android/pull/2454#issuecomment-449423712

As of commit a4a7fda6, `jnimarshalmethod-gen.exe` will *update* the
"original" assemblies, meaning this:

	mono jnimarshalmethod-gen.exe --jvm ... Foo.dll

will *in-place rewrite* `Foo.dll` to contain the required
JNI marshal methods.

Unfortunately, this doesn't work on Windows, because `Foo.dll` will
be opened-for-Reflection as part of `jnimarshalmethod-gen.exe`
processing, and thus writing to `Foo.dll` causes all manner of pain:

	Error: jnimarshalmethod-gen: Unable to process assembly 'obj\Release\81\linksrc\MobileApp2.Android.dll'
	Win32 IO returned 1224. Path: C:\…\MobileApp2.Android\obj\Release\81\linksrc\MobileApp2.Android.dll
	System.IO.IOException: Win32 IO returned 1224. Path: C:\…\MobileApp2.Android\obj\Release\81\linksrc\MobileApp2.Android.dll
	  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options)
	  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share)
	  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
	  at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share)
	  at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
	  at Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.TypeMover.Move ()
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly (System.String path)
	  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1[T] assemblies)	

Error code 1224 is [`ERROR_USER_MAPPED_FILE`][0]:

> The requested operation cannot be performed on a file with a
> user-mapped section open.

Meaning the default operation of `jnimarshalmethod-gen.exe`
*cannot work on Windows*.

Oops.

Add a new `jnimarshalmethod-gen.exe -o DIR` option, so that the newly
written assemblies can be written into `DIR` instead of in-place
updating the assemblies as done in a4a7fda6.

This *should* allow `jnimarshalmethod-gen.exe` to work on Windows.

[0]: https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--1000-1299-

`jnimarshalmethod-gen.exe` doesn't work as desired on Windows