Fix property setter generation
Context: https://github.com/xamarin/xamarin-android/pull/8339

While testing on xamarin/xamarin-android#8339, we hit this error
(among others, to be addressed later):

	src/Mono.Android/obj/Debug/net8.0/android-34/mcw/Android.Views.IWindowInsetsController.cs(304,41): error CS0103: The name 'behavior' does not exist in the current context

This was caused because of code such as:

	public partial interface IWindowInsetsController {
		public unsafe int SystemBarsBehavior {
			get {
				const string __id = "getSystemBarsBehavior.()I";
				try {
					var __rm = _members_IWindowInsetsController.InstanceMethods.InvokeAbstractInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
			set {
				const string __id = "setSystemBarsBehavior.(I)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue (behavior);
					_members_IWindowInsetsController.InstanceMethods.InvokeAbstractVoidMethod (__id, this, __args);
				} finally {
				}
			}
		}
	}

This happened because when emitting the property setter, we need
to update the `set*` method's parameter name to be `value` so that
the normal property setter body is emitted properly.

Update `InterfaceInvokerProperty.cs` so that the parameter name
is set to `value`.

Update `tests/generator-Tests/Integration-Tests/Interfaces.cs`
so that we test interface generation for JavaInterop1.

Update `tests/generator-Tests/SupportFiles/*.cs` so that
`Interfaces.cs` test output can be compiled.

Update `tests/generator-Tests/expected.ji/TestInterface/TestInterface.xml`
so that some parameter names for `set*()` methods are *not* already
named `value`, to induce the original error.

Flush `tests/generator-Tests/expected.ji/TestInterface`.