[tests] Add net6.0 TargetFramework. (#888)
Today, even when building and testing on .NET 6, most of our test
suites are still building and running with `net472`.

Fix this by adding `net6.0` to `$(TargetFrameworks)` and updating CI
to run the `net6.0` version instead of the `net472` version.

Fixes were required to account for differences between `net472` and
`net6.0` behavior, in particular:

  * The semantics for the [Round-trip format specifier `R`][0]
    changed between .NET Framework and .NET 6.
    Update `ConstantPoolFloatItem.ToString()` and
    `ConstantPoolDoubleItem.ToString()` to use the G9 and G17
    format specifiers, respectively, so that behavior is consistent.

  * Types such as `System.String` moved from `mscorlib.dll` to
    `System.Private.CoreLib.dll`, which impacts the output of
    `JavaNativeTypeManager.GetPackageName()`, as the assembly name
    is taken into consideration.  Assertions around
    `JavaNativeTypeManager.GetPackageName()` need to be based on the
    target framework.

  * When using `CSharpCompilation.Create()`, `System.Runtime.dll`
    must now be referenced when building on net6+, otherwise certain
    types won't be resolved:

        error CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (SourceFile([871..891)))
        error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (SourceFile([944..962)))
        error CS0012: The type 'IDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (SourceFile([312..321)))

  * `MarshalMemberBuilderTest.cs` must be disabled when building for
    .NET 6+, as `AssemblyBuilderAccess.Save` doesn't exist, nor does
    `AppDomain.DefineDynamicAssembly()`, nor
    `LambdaExpression.CompileToMethod()`.
    Related: https://github.com/xamarin/java.interop/issues/616

        error CS0117: 'AssemblyBuilderAccess' does not contain a definition for 'Save'
        error CS1061: 'AppDomain' does not contain a definition for 'DefineDynamicAssembly' and no accessible extension method 'DefineDynamicAssembly' accepting a first argument of type 'AppDomain' could be found (are you missing a using directive or an assembly reference?)
        error CS1061: 'LambdaExpression' does not contain a definition for 'CompileToMethod' and no accessible extension method 'CompileToMethod' accepting a first argument of type 'LambdaExpression' could be found (are you missing a using directive or an assembly reference?)

[0]: https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#round-trip-format-specifier-r