[java-interop] Selectively keep DylibMono for Xamarin.Android
Context: https://github.com/xamarin/xamarin-android/pull/3504
Context: https://github.com/xamarin/xamarin-android/pull/3223

When bumping xamarin-android/master to 2abfc1e0, the build broke
because of commit 285a32b3:

	  In file included from /Users/vsts/agent/2.155.1/work/1/s/external/Java.Interop/src/java-interop/java-interop-mono.cc:2:
	  ../../../../../external/Java.Interop/src/java-interop/java-interop-mono.h:10:11: fatal error: 'mono/metadata/assembly.h' file not found
	          #include <mono/metadata/assembly.h>
	                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
	  1 error generated.

We need to continue supporting the DylibMono backend for integration
purposes (xamarin/xamarin-android#3504) *while also* allowing for the
*removal* of DylibMono (xamarin/xamarin-android#3223).

Attempt to support these divergent needs by replacing this:

	#if defined (ANDROID) || defined (XAMARIN_ANDROID_DYLIB_MONO)

with this:

	#if defined (XAMARIN_ANDROID_DYLIB_MONO)

removing the check for the `ANDROID` define.

This will allow xamarin/xamarin-android#3223 to *remove* the
`XAMARIN_ANDROID_DYLIB_MONO` definition in order to introduce it's
desired behavior, removing DylibMono use.

This partially reverts commit 285a32b3.