Test XAJavaInterop1 output
Trying to build in xamarin-android resulted in lots of errors:

    …/mcw/Android.Text.IInputType.cs(34,17): error CS0122: 'Object._members' is inaccessible due to its protection level

Oops.

Looks like at least *some* tests need to run w/ XAJavaInterop1 output!

Update `BaseGeneratorTest` to use `XAJavaInterop1` output for the
tests, update `generator` so that the tests *pass*, and update the
expected output accordingly.