MOAR printf logging!
`-v:diag` looks reasonable, in that `$(_MonoNativePath)` contained a
value which looked like what I expected.

Yet the build still fails:

    In file included from /Users/runner/work/1/s/src/java-interop/java-interop-gc-bridge-mono.cc:10: (TaskId:621)
    /Users/runner/work/1/s/src/java-interop/java-interop-mono.h:6:10: fatal error: 'mono/metadata/assembly.h' file not found (TaskId:621)
    #include <mono/metadata/assembly.h> (TaskId:621)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~ (TaskId:621)
     (TaskId:621)

I must assume that while the properties have expected values, the
*contents on disk* are…missing?  Or something?

Start logging what's there.