[java-interop] Added missing logger implementation
The `java-interop-logger.c` was not used to build java-interop shared
library. Thus any usage of `log_*` functions led to crash, because the
function was missing. Like:

    dyld: lazy symbol binding failed: Symbol not found: _log_error
      Referenced from: /Users/rodo/git/java.interop/bin/Debug/libjava-interop.dylib
      Expected in: flat namespace

    dyld: Symbol not found: _log_error
      Referenced from: /Users/rodo/git/java.interop/bin/Debug/libjava-interop.dylib
      Expected in: flat namespace

    Stacktrace:

      at <unknown> <0xffffffff>
      at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jvm_load (string) [0x00013] in <ce3946f6ded84ae7a635a712310f3fc9>:0
      at Java.Interop.JreRuntime.CreateJreVM (Java.Interop.JreRuntimeOptions) [0x00045] in /Users/rodo/git/java.interop/src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs:92
      at Java.Interop.JreRuntime..ctor (Java.Interop.JreRuntimeOptions) [0x00000] in /Users/rodo/git/java.interop/src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs:133
      at Java.Interop.JreRuntimeOptions.CreateJreVM () [0x00001] in /Users/rodo/git/java.interop/src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs:72
      at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateJavaVM (string) [0x00010] in /Users/rodo/git/java.interop/tools/jnimarshalmethod-gen/App.cs:194
      at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1<string>) [0x00001] in /Users/rodo/git/java.interop/tools/jnimarshalmethod-gen/App.cs:144
      at (wrapper remoting-invoke-with-check) Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1<string>) [0x00033] in <3425156c0c424f7eadc43572ca191f64>:0
      at (wrapper xdomain-dispatch) Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (object,byte[]&,byte[]&) [0x00043] in <3425156c0c424f7eadc43572ca191f64>:0
      at (wrapper xdomain-invoke) Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1<string>) <0x001c0>
      at (wrapper remoting-invoke-with-check) Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies (System.Collections.Generic.List`1<string>) [0x00027] in <3425156c0c424f7eadc43572ca191f64>:0
      at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.Main (string[]) <0x001e2>
      at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0x0010c>

The existing `java-interop-logger.c` was only used in XA to build
`monoandroid` shared library. The new implementation replaces it and
the original `java-interop-logger.c` will move back to XA.