MOAR PRINTFS
This is quite confusing; as per CI logs, during `dotnet publish`:

      Hello-NativeAOTFromJNI -> /Users/runner/work/1/s/samples/Hello-NativeAOTFromJNI/bin/Release/osx-x64/publish/

which implies to me that `/Users/runner/work/1/s/samples/Hello-NativeAOTFromJNI/bin/Release/osx-x64/publish`
*exists*.

However, when we get to `dotnet build -t:RunJavaSample`:

    ##[error]samples/Hello-NativeAOTFromJNI/Hello-NativeAOTFromJNI.targets(106,5): Error MSB6003: The specified task executable "sh" could not be run.
      System.IO.DirectoryNotFoundException: The working directory
      "/Users/runner/work/1/s/samples/Hello-NativeAOTFromJNI/bin/Release/osx-x64/publish/"
      does not exist.

Which looks the same to me!

Dump out dir contents.