Remove support for win-x86.
Means I don't need to worry about 32-bit vs. 64-bit `coreclr.lib` files.

With this change, the following (terrible hack) "works":

```
dotnet build -c Release -t:Prepare -p:DotNetTargetFramework=net8.0 Java.Interop.sln
dotnet build -c Release -p:DotNetTargetFramework=net8.0 Java.Interop.sln

dotnet publish --self-contained -p:UseMonoRuntime=true -p:DotNetTargetFramework=net8.0 -p:UseAppHost=true -p:ErrorOnDuplicatePublishOutputFiles=false -r win-x64 samples/Hello-Java.Base/Hello-Java.Base.csproj

copy samples\Hello-Java.Base\bin\Release\Hello-Java.Base.jar samples\Hello-Java.Base\bin\Release\win-x64

dotnet build -c Release -p:DotNetTargetFramework=net8.0 -r win-x64 src\java-interop\java-interop.csproj
copy bin\Release-net8.0\win-x64\win-x64 samples\Hello-Java.Base\bin\Release\win-x64
```

...until you try to *run* the app, then it fails:

	> samples\Hello-Java.Base\bin\Release\win-x64\Hello-Java.Base.exe
	MonoVM support enabled
	# jonp: LoadJvmLibrary(C:\Users\jopryo\android-toolchain\jdk-1.8\jre\bin\server\jvm.dll)=1344667648
	# jonp: JNI_CreateJavaVM=1345963424; JNI_GetCreatedJavaVMs=1345963728
	# jonp: executing JNI_CreateJavaVM=5039c5a0
	# jonp: r=0 javavm=509e0650 jnienv=13e1d0b6a58
	WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethodV
	WARNING in native method: JNI call made with exception pending
	WARNING in native method: JNI call made with exception pending

	Unhandled Exception:
	System.TypeInitializationException: The type initializer for 'Types' threw an exception.
	 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'method')
	   at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method) in Q:\src\dotnet\java-interop\src\Java.Interop\obj\Release\net8.0\JniEnvironment.g.cs:line 19974

...but that's because it's using *JDK 1.8*.

Tell it to use JDK 11+ (17+?), and it works!

	>samples\Hello-Java.Base\bin\Release\win-x64\Hello-Java.Base.exe --jvm C:\Users\jopryo\android-toolchain\jdk-17\bin\server\jvm.dll
	MonoVM support enabled
	# jonp: LoadJvmLibrary(C:\Users\jopryo\android-toolchain\jdk-17\bin\server\jvm.dll)=140710737870848
	# jonp: JNI_CreateJavaVM=140710742010000; JNI_GetCreatedJavaVMs=140710742010032
	# jonp: executing JNI_CreateJavaVM=7ff9c5cb2890
	# jonp: r=0 javavm=7ff9c63dd7f0 jnienv=15f85f0a0e0
	WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethodV
	binding? net.dot.jni.sample.MyJLO@a09ee92