Fix JdkJvmPath probing
Context: 224433e182b78253d55ea9068de89b1853337845

Remember 224433e1?

> ...until you try to *run* the app, then it fails:
>
>         > samples\Hello-Java.Base\bin\Release\win-x64\Hello-Java.Base.exe
>         MonoVM support enabled
>         # jonp: LoadJvmLibrary(C:\Users\jopryo\android-toolchain\jdk-1.8\jre\bin\server\jvm.dll)=1344667648
>         # jonp: JNI_CreateJavaVM=1345963424; JNI_GetCreatedJavaVMs=1345963728
>         # jonp: executing JNI_CreateJavaVM=5039c5a0
>         # jonp: r=0 javavm=509e0650 jnienv=13e1d0b6a58
>         WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethodV
>         WARNING in native method: JNI call made with exception pending
>         WARNING in native method: JNI call made with exception pending
>
>         Unhandled Exception:
>         System.TypeInitializationException: The type initializer for 'Types' threw an exception.
>
> ...but that's because it's using *JDK 1.8*.
>
> Tell it to use JDK 11+ (17+?), and it works!
>
>         >samples\Hello-Java.Base\bin\Release\win-x64\Hello-Java.Base.exe --jvm C:\Users\jopryo\android-toolchain\jdk-17\bin\server\jvm.dll
>         MonoVM support enabled
>         # jonp: LoadJvmLibrary(C:\Users\jopryo\android-toolchain\jdk-17\bin\server\jvm.dll)=140710737870848
>         # jonp: JNI_CreateJavaVM=140710742010000; JNI_GetCreatedJavaVMs=140710742010032
>         # jonp: executing JNI_CreateJavaVM=7ff9c5cb2890
>         # jonp: r=0 javavm=7ff9c63dd7f0 jnienv=15f85f0a0e0
>         WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethodV
>         binding? net.dot.jni.sample.MyJLO@a09ee92

Update `TestJVM.GetJvmLibraryPath()` to probe for more locations.
It was previously assuming that the assembly would be located within
`bin/Tests*`, which isn't the case for the sample.  It now will find
`<checkout>\bin\Build{Debug,Release}\JdkInfo.props`, avoiding the need
to provide the `--jvm=PATH` argument.

Additionally, `java-interop.targets` was occasionally failing to build
from `samples\Hello-Java.Base` because it was trying to build
`libjava-interop.dylib` for arm64 on my x86 machine, which is not
supported.  (Not sure why this didn't break before.)