[Java.Interop.Tools.Cecil] DirectoryAssemblyResolver.ToResolverCache returns a Dictionary (#152)
This is needed as part of
[bumping xamarin-android to use mono/2017-06][0], to fix the
following compilation error:

    Tasks/LinkAssemblies.cs(103,41): error CS1503: Argument 1: cannot convert from 'System.Collections.IDictionary' to 'System.Collections.Generic.Dictionary<string, Mono.Cecil.AssemblyDefinition>'

[0]: https://github.com/xamarin/xamarin-android/pull/631