[jnimarshalmethod-gen] Generate helpers for methods with Register CA
Updated the generator to generate helper marshaling methods for
classes implementing `Java.Interop.IJavaPeerable` interface and their
methods with `Android.Runtime.RegisterAttribute` custom
attribute. Plus `__RegisterNativeMembers` method to register these
methods during runtime.

It is part of https://github.com/xamarin/xamarin-android/projects/1
project.

The JniRuntime.JniMarshalMemberBuilder.cs change is a workaround for
BCL bug, which causes this exception:
```
Error: jnimarshalmethod-gen: Unable to process assembly '/Users/rodo/Projects/xatemplateaot/xatemplateaot/obj/Debug/android/assets/Mono.Android.dll'
Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at System.Attribute.InternalParamGetCustomAttributes (System.Reflection.ParameterInfo parameter, System.Type attributeType, System.Boolean inherit) [0x0005b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/attribute.cs:60
  at System.Attribute.GetCustomAttributes (System.Reflection.ParameterInfo element, System.Type attributeType, System.Boolean inherit) [0x0008b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/attribute.cs:681
  at System.Attribute.GetCustomAttribute (System.Reflection.ParameterInfo element, System.Type attributeType, System.Boolean inherit) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/attribute.cs:749
  at System.Attribute.GetCustomAttribute (System.Reflection.ParameterInfo element, System.Type attributeType) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/attribute.cs:742
  at System.Reflection.CustomAttributeExtensions.GetCustomAttribute (System.Reflection.ParameterInfo element, System.Type attributeType) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/reflection/CustomAttributeExtensions.cs:22
  at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T] (System.Reflection.ParameterInfo element) [0x00000] in <e36d106f4822473d8910305e5d059e11>:0
  at Java.Interop.JniRuntime+JniMarshalMemberBuilder.GetParameterMarshaler (System.Reflection.ParameterInfo parameter) [0x0001f] in /Users/rodo/git/clean-full/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs:138
  at Java.Interop.MarshalMemberBuilder.CreateMarshalToManagedExpression (System.Reflection.MethodInfo method, Java.Interop.JavaCallableAttribute callable, System.Type type) [0x002f1] in /Users/rodo/git/clean-full/xamarin-android/external/Java.Interop/src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs:182
  at Java.Interop.MarshalMemberBuilder.CreateMarshalToManagedExpression (System.Reflection.MethodInfo method) [0x00014] in /Users/rodo/git/clean-full/xamarin-android/external/Java.Interop/src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs:32
  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly (System.String path) [0x00272] in /Users/rodo/git/clean-full/xamarin-android/external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:183
  at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.Main (System.String[] args) [0x001a5] in /Users/rodo/git/clean-full/xamarin-android/external/Java.Interop/tools/jnimarshalmethod-gen/App.cs:67
```