[Java.Interop.BootstrapTasks] Support single-digit versions
The `<JdkInfo/>` task sorts preferred JDK versions based on the
version number embedded into the directory name.

This unfortunately requires that the version number embedded into the
directory name contain two or more version parts.  This is true on
macOS and Windows:

	# macOS
	$ ls -1tr /Library/Java/JavaVirtualMachines/
	1.6.0_65-b14-462.jdk
	jdk1.8.0_77.jdk
	jdk-9.0.4.jdk

But this is not necessarily the case on Linux:

	$ ls -1 /usr/lib/jvm
	java-8-openjdk-amd64
	java-8-oracle

Single-part version numbers aren't supported by `Version.TryParse()`,
so when `$(JI_MAX_JDK)` is set -- causing `maxVersion` to be non-null
-- while the version *isn't* extracted from the directory name, the
[comparison can fail][0]:

[0]: https://jenkins.mono-project.com/job/xamarin-anroid-linux-pr-builder/2917/console

	The "JdkInfo" task failed unexpectedly.
	System.ArgumentNullException: Value cannot be null.
	Parameter name: v1
	  at System.Version.op_LessThanOrEqual (System.Version v1, System.Version v2) [0x00003] in <2f83d2ff70e3444cb3582fe4e97bad63>:0
	  at Java.Interop.BootstrapTasks.JdkInfo+<>c__DisplayClass31_0.<GetJavaHomePathFromMachine>b__2 (<>f__AnonymousType0`2[<Path>j__TPar,<Version>j__TPar] v) [0x00000] in …/xamarin-android/external/Java.Interop/src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs:172
	  ...
	  at Java.Interop.BootstrapTasks.JdkInfo.GetJavaHomePathFromMachine (System.Version maxVersion) [0x00015] in …/xamarin-android/external/Java.Interop/src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs:163
	  at Java.Interop.BootstrapTasks.JdkInfo.Execute () [0x00176] in …/xamarin-android/external/Java.Interop/src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs:56

Fix this by allowing extraction of Version numbers from single-part
version codes as seen on Linux, allowing us to perform comparisons
against non-null versions.  If multiple directories *still* have
matching version numbers, then we sort the output so that the location
with the most recent write time is used.

Additionally, check some OS-specific preferred locations:

  * On macOS, `/usr/libexec/java_home`, which is a program which
    prints out the preferred JDK location to stdout.
  * On Linux, `/usr/alternatives/java` is a symlink to the preferred
    JDK location, which we can read using `readlink`.

Treat the OS-specific locations similar to `$JAVA_HOME`, and check
them *before* attempting the `JdkInfo.JdksRoot` children.