Work with .NET 8 GA (…?)
The Hello-NativeAOTFromJNI sample previously built and worked on
.NET 8 RC2 on macOS+x64, but when I tried things on .NET 8 GA on
macOS+arm64, things failed "inexplicably"

	% dotnet publish -c Release -r osx-x64
	EXEC : error JM4006: jnimarshalmethod-gen: Unable to process assembly '/Users/jon/Developer/src/xamarin/java.interop/samples/Hello-NativeAOTFromJNI/bin/Release/osx-x64/Hello-NativeAOTFromJNI.dll' [/Users/jon/Developer/src/xamarin/java.interop/samples/Hello-NativeAOTFromJNI/Hello-NativeAOTFromJNI.csproj]
	  Could not load file or assembly 'Hello-NativeAOTFromJNI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	  System.IO.FileLoadException: Could not load file or assembly 'Hello-NativeAOTFromJNI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
	     at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
	     at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.CreateMarshalMethodAssembly(String path) in /Users/jon/Developer/src/xamarin/java.interop/tools/jnimarshalmethod-gen/App.cs:line 445
	     at Xamarin.Android.Tools.JniMarshalMethodGenerator.App.ProcessAssemblies(List`1 assemblies) in /Users/jon/Developer/src/xamarin/java.interop/tools/jnimarshalmethod-gen/App.cs:line 272

After a few days of pulling my hair out, @lambdageek suggested:

> so maybe coreclr on arm64 refuses to load a PE32+ image that is x86-64?

This turns out to be the case, presenting two "workarounds":

 1. Build with an rid that matches the host platform, e.g. this worked:

        dotnet publish -c Release -r osx-arm64

 2. Setting `$(PlatformTarget)`=AnyCPU also works, as the resulting
    assembly isn't tied to a specific rid.

Update `Hello-NativeAOTFromJNI.csproj` to set
`$(PlatformTarget)`=AnyCPU, so that I can at least *build*
osx-x64 from osx-arm64.  (I can't *run* it, but I can build it!)

Also update `jnimarshalmethod-gen` to not load assemblies from
directories containing `/ref/`, as reference assemblies cannot be
loaded for execution:

	System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.
	 ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies cannot be loaded for execution. (0x80131058)
	File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies cannot be loaded for execution. (0x80131058)
	File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
	   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
	   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
	   at System.Reflection.Assembly.LoadFile(String path)