[generator] Disable [SupportedOSPlatform] until .NET 5/6. (#781)
Context: da12df4535422f2aaf3a7570326336b30cd50b55
Context: a33084b381c4871d7898c0ae2de5ed698c6943bc
Context: https://github.com/xamarin/xamarin-android/pull/5497#pullrequestreview-568088000

We cannot currently build `net5.0` or `net6.0` assemblies in our
xamarin-android tree; we instead do some workaround that involves
compiling with `netcoreapp3.1` while referencing the 5.0 BCL.

This creates a conflict between the local `[SupportedOSPlatform]` we
create in `Mono.Android.dll` built for `netcoreapp3.1` , and the real
one in the 5.0 BCL.

	error CS0433: The type 'SupportedOSPlatformAttribute' exists in both
	'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and
	'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
	[/Users/runner/work/1/s/tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj]

Disable generating `SupportedOSPlatformAttribute` until we can build
`Mono.Android.dll` with `NET` defined, in which case it will not
contain the local attribute, and we can re-enable da12df45.