"Full(er)" sample
What `Hello-NativeAOTFromJNI` previously did was quite minimal:

 1. Use `[UnmanagedCallersOnly]` to provide a `JNI_OnLoad()` method which
 2. Initialized the Java.Interop runtime, allowing
 3. An `[UnmanagedCallersOnly]`-provided `Java_…` method which is called from Java.

All quite low level, all miles away from .NET Android.

Expand the sample to:

 1. Contain a `Java.Lang.Object` subclass, which contains a
    `[JavaCallable]` method.
 2. Call `jcw-gen` to generate Java Callable Wrappers for (1),
    containing the `[JavaCallable]` method.
 3. Call `jnimarshalmethod-gen` to generate marshal methods for (1),
    as NativeAOT doesn't support System.Reflection.Emit.
 4. Instantiate (1) *from Java*, and invoke the `[JavaCallable]` method.

*Now* we're (kinda) getting something that looks like .NET Android.

But first, we need to make that *work*:

Update `Java.Interop.Tools.JavaCallableWrappers` so that it will emit
`native` method declarations for `[JavaCallable]` methods, not just
method overrides and `[Export]` methods.

Update `Java.Interop.Tools.Expressions` so that the `_JniMarshal_*`
delegate types have `[UnmanagedFunctionPointer(CallingConvention.Winapi)]`,
as this is what allows NativeAOT to emit appropriate "stubs"; see
also da9f188d8ffc19cc15a5dd90810151c378d73c56.

Update `Java.Interop.Tools.Expressions.ExpressionAssemblyBuilder` to
no longer attempt to "remove and fixup" `System.Private.CoreLib`.
So long as `ExpressionAssemblyBuilder` output is *only* used in
"completed" apps (not distributed in NuGet packages in some
"intermediate" form), referencing `System.Private.CoreLib` is "fine".
Additionally, trying to remove `System.Private.CoreLib` broke things
when adding `[UnmanagedFunctionPointer]`, as `CallingConvention`
could not be resolved, resulting in `jnimarshalmethod-gen` erroring
out with:

	error JM4006: jnimarshalmethod-gen: Unable to process assembly '/Volumes/Xamarin-Work/src/xamarin/Java.Interop/samples/Hello-NativeAOTFromJNI/bin/Debug/Hello-NativeAOTFromJNI.dll'
	Failed to resolve System.Runtime.InteropServices.CallingConvention
	Mono.Cecil.ResolutionException: Failed to resolve System.Runtime.InteropServices.CallingConvention
	   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
	   at Mono.Cecil.SignatureWriter.WriteCustomAttributeEnumValue(TypeReference enum_type, Object value)
	   …

(This is because `CallingConvention` is in
`System.Runtime.InteropServices.dll`, which isn't referenced.)

We could "fix" this by explicitly adding a reference to
`System.Runtime.InteropServices.dll`, but this is just one of an
unknown number of corner cases.  Give up for now.

Update `jnimarshalmethod-gen` assembly location probing: it
was given the *full assembly name* of `Java.Base`:

	# jonp: resolving assembly: Java.Base, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null

…and failing to find `Java.Base.dll`, because it was looking for
`Java.Base, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null.dll`.
Oops.

Use `AssemblyName` to parse the string and extract out the assembly
name., so that `Java.Base.dll` is probed for and found.

With all that…it still fails:

	% (cd bin/Release/osx-x64/publish ; java -cp hello-from-java.jar:java-interop.jar com/microsoft/hello_from_jni/App)
	Hello from Java!
	C# init()
	Hello from .NET NativeAOT!
	String returned to Java: Hello from .NET NativeAOT!
	Exception in thread "main" com.xamarin.java_interop.internal.JavaProxyThrowable: System.IO.FileNotFoundException: Could not resolve assembly 'Hello-NativeAOTFromJNI'.
	   at System.Reflection.TypeNameParser.ResolveAssembly(String) + 0x97
	   at System.Reflection.TypeNameParser.GetType(String, ReadOnlySpan`1, String) + 0x32
	   at System.Reflection.TypeNameParser.NamespaceTypeName.ResolveType(TypeNameParser&, String) + 0x17
	   at System.Reflection.TypeNameParser.GetType(String, Func`2, Func`4, Boolean, Boolean, Boolean, String) + 0x99
	   at Java.Interop.ManagedPeer.RegisterNativeMembers(IntPtr jnienv, IntPtr klass, IntPtr n_nativeClass, IntPtr n_assemblyQualifiedName, IntPtr n_methods) + 0x103
		at com.xamarin.java_interop.ManagedPeer.registerNativeMembers(Native Method)
		at example.ManagedType.<clinit>(ManagedType.java:15)
		at com.microsoft.hello_from_jni.App.main(App.java:13)

`App.main()` has `new example.ManagedType()`, which hits the
`ManagedType` static constructor of:

	public /* partial */ class ManagedType
	  extends java.lang.Object
	  implements
	    com.xamarin.java_interop.GCUserPeerable
	{
	/** @hide */
	  public static final String __md_methods;
	  static {
	    __md_methods =
	      "n_GetString:()Ljava/lang/String;:__export__\n" +
	      "";
	    com.xamarin.java_interop.ManagedPeer.registerNativeMembers (ManagedType.class, "Example.ManagedType, Hello-NativeAOTFromJNI", __md_methods);
	  }
	}

The `ManagedPeer.registerNativeMembers()` call is what is needed
to register the native `ManagedPeer.getString()` method, so that
it can be called.  This is good.  (Though `__md_methods` containing
*anything* is not desired, but that's a different problem.)

`ManagedPeer.RegisterNativeMembers()` is given the assembly-qualified
name `Example.ManagedType, Hello-NativeAOTFromJNI`, and tries to:

	Type.GetType ("Example.ManagedType, Hello-NativeAOTFromJNI", throwOnError: true);

…which then proceeds to throw, because in NativeAOT
*there are no assemblies*, and thus `Type.GetType()` *cannot work*.

Oops.

Thus, the only way to make something remotely like .NET Android
infrastructure work is to *require* the use of `Java_…` native method
names and `[UnmanagedCallersOnly]` on marshal methods.
(In .NET Android parlance, the experimental
`$(AndroidEnableMarshalMethods)`=True is required.)