[build] Java.Interop-MonoAndroid wildcards too much
Downstream in xamarin/xamarin-android, running:

    msbuild Xamarin.Android.sln
    msbuild Xamarin.Android.sln /p:Configuration=Release

You run into an odd build error:

    (CoreCompile target) ->
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
        obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(21,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute

The `@(Compile)` item group included:

    obj\Debug\netstandard2.0\Java.Interop.AssemblyInfo.cs
    obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs

We have a wildcard in this project to emulate SDK-style projects:

    <Compile Include="**\*.cs" />

We need to exclude `obj` and `obj-MonoAndroid` from this wildcard.