[Java.Interop] JavaTypeParametersAttribute only in net6
Context: https://github.com/xamarin/xamarin-android/pull/6549

When attempting to bump xamarin-android to use bc5bcf4f, the build
failed because bc5bcf4f added a "duplicate" type
`Java.Interop.JavaTypeParametersAttribute`:

	error CS0433: The type 'JavaTypeParametersAttribute' exists in both
	'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and
	'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.

The plan was to use type forwarders for this type from
`Mono.Android.dll` to `Java.Interop.dll`, but in retrospect this
sounds like a potential "forward-incompatible ABI break" (e56a8c8e)
as assemblies built against the newer `Mono.Android.dll` (with type
forwarders) won't be usable on previous Xamarin.Android SDKs.

Make `JavaTypeParametersAttribute` conditional on `NET`, so that it's
only included in .NET 6 builds.  .NET SDK for Android will then use
type forwarders, which won't be an issue as there's no previous .NET
release to be forward compatible with.

Update `tests/generator-Tests` so that `JavaTypeParametersAttribute`
is once again provided for non-`NET` builds.