[generator] Qualify `object.GetType()` invocations
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=45203
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=44263#c8

(Sorry; private bugs.)

The `getType()` method isn't special; any Java library could contain
such a method:

	// Java
	public class Example {
		public int[] getType() {return null;}
	}

(It's a wonder that we haven't hit such a thing before!)

Unfortunately, should such a method (1) exist, and (2) be bound as
`GetType()` instead of as a `Type` property -- in the above example,
we use an `int[]` return type because if a Java method has an array
return type, we won't turn it into a property -- the resulting code
wouldn't compile:

	// error CS0019: Operator `==' cannot be applied to operands of type `int[]' and `System.Type'
	if (GetType () == ThresholdType) ...

To fix this, *qualify* all use of the `GetType()` method so that we
explicitly use `System.Object.GetType()`:

	if ((object) this).GetType () == ThresholdType) ...

This has no performance-impact, IL-wise, as the C# compiler is able to
statically determine that we want non-virtual invocation of the
`System.Object.GetType()` method. No runtime cast is performed.