[class-parse] Fix build break from 806082f2
Fix a [build][0] [break][1] from commit 806082f2:

	Program.cs(97,35): error CS0117: `Xamarin.Android.Tools.Bytecode.JavaDocletType' does not contain a definition for `ApiXml'

It should be referencing `_ApiXml`, not `ApiXml`.

[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/Java.Interop/94/
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/Java.Interop/94/console