[build] disable $(GenerateAssemblyInfo) in Java.Interop
This partially reverts 85be94f, except I kept the use of "Microsoft
Corporation".

Since `Java.Interop-MonoAndroid.csproj` is a non-SDK style project, we
should set `$(GenerateAssemblyInfo)` to `False` and use the old way of
defining assembly-level attributes with `Properties\AssemblyInfo.cs`.

This way we can properly include the following attributes when
`Java.Interop-MonoAndroid.csproj` is built:

    [assembly: AssemblyTitle ("Java.Interop")]
    [assembly: AssemblyDescription ("")]
    [assembly: AssemblyConfiguration ("")]
    [assembly: AssemblyCompany ("Microsoft Corporation")]
    [assembly: AssemblyProduct ("")]
    [assembly: AssemblyCopyright ("Microsoft Corporation")]
    [assembly: AssemblyTrademark ("Microsoft Corporation")]
    [assembly: AssemblyCulture ("")]
    [assembly: AssemblyVersion ("0.1.0.0")]

The `AssemblyVersion` is the most important attribute here, which
would otherwise cause errors downstream in Xamarin.Android such as:

    MainActivity.cs(40,81): error CS1705: Assembly 'Xamarin.Android.Support.Fragment' with identity 'Xamarin.Android.Support.Fragment, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

Strong-naming, yay!